/**
 * Generate version module
 *
 * This script reads the version from package.json and generates
 * a TypeScript module at src/shared/version/index.ts with version
 * constants and utility functions.
 *
 * Run before build to ensure version is up to date.
 */

import { mkdir, readFile, writeFile } from "fs/promises";
import { join } from "path";

const PACKAGE_JSON = "./package.json";
const OUTPUT_DIR = "./src/shared/version";
const OUTPUT_FILE = join(OUTPUT_DIR, "index.ts");

async function main() {
	console.log("Generating version module...\n");

	// Read package.json
	let packageJson: { version?: string };
	try {
		const content = await readFile(PACKAGE_JSON, "utf-8");
		packageJson = JSON.parse(content);
	} catch (err) {
		console.error(`Error: Failed to read ${PACKAGE_JSON}:`, err);
		process.exit(1);
	}

	// Validate version exists
	if (!packageJson.version) {
		console.error(`Error: No version field found in ${PACKAGE_JSON}`);
		process.exit(1);
	}

	const version = packageJson.version;

	// Validate semantic versioning format (x.y.z)
	const semverRegex = /^\d+\.\d+\.\d+$/;
	if (!semverRegex.test(version)) {
		console.error(
			`Error: Version "${version}" does not match x.y.z format (semantic versioning)`,
		);
		console.error('Expected format: "1.0.0" or "2.3.4"');
		process.exit(1);
	}

	// Parse version components
	const [major, minor, patch] = version.split(".").map(Number);

	// Generate TypeScript module
	const code = `/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by scripts/generate-version.ts
 *
 * Version: ${version}
 * Generated: ${new Date().toISOString()}
 */

/**
 * Application version constant
 */
export const VERSION = "${version}";

/**
 * Version components
 */
export const VERSION_MAJOR = ${major};
export const VERSION_MINOR = ${minor};
export const VERSION_PATCH = ${patch};

/**
 * Get version string with optional prefix
 * @param prefix - Optional prefix (e.g., "v" for "v1.0.0")
 * @returns Formatted version string
 */
export function getVersionString(prefix = ""): string {
	return \`\${prefix}\${VERSION}\`;
}

/**
 * Get version components as object
 * @returns Object with major, minor, patch
 */
export function getVersionComponents(): {
	major: number;
	minor: number;
	patch: number;
} {
	return {
		major: VERSION_MAJOR,
		minor: VERSION_MINOR,
		patch: VERSION_PATCH,
	};
}
`;

	// Ensure output directory exists
	await mkdir(OUTPUT_DIR, { recursive: true });

	// Write the module
	await writeFile(OUTPUT_FILE, code, "utf-8");

	console.log(`✓ Generated version module: ${OUTPUT_FILE}`);
	console.log(`  Version: ${version}`);
	console.log(`  Components: ${major}.${minor}.${patch}`);
	console.log("\n✓ Version generation complete");
}

main().catch(console.error);
