/**
 * Generate embedded assets module
 *
 * This script scans the built frontend and prompts directories,
 * then generates TypeScript modules that embed all content as strings.
 *
 * Run after frontend build, before backend build.
 */

import { mkdir, readdir, readFile, writeFile } from "fs/promises";
import { extname, join } from "path";
import { getMimeType } from "../src/shared/utils/mime-types";

const FRONTEND_DIST = "./frontend/dist";
const PROMPTS_EVALUATORS = "./prompts/evaluators";
const PROMPTS_SHARED = "./prompts/shared";
const OUTPUT_DIR = "./src/embedded";

async function scanDirectoryRecursive(
	dir: string,
	relativePath: string = "",
): Promise<string[]> {
	try {
		const entries = await readdir(dir, { withFileTypes: true });
		const files: string[] = [];

		for (const entry of entries) {
			const entryPath = join(dir, entry.name);
			const entryRelativePath = relativePath
				? `${relativePath}/${entry.name}`
				: entry.name;

			if (entry.isDirectory()) {
				// Recursively scan subdirectories
				const subFiles = await scanDirectoryRecursive(
					entryPath,
					entryRelativePath,
				);
				files.push(...subFiles);
			} else if (entry.isFile()) {
				files.push(entryRelativePath);
			}
		}

		return files;
	} catch {
		return [];
	}
}

async function generateFrontendModule(): Promise<void> {
	const files = await scanDirectoryRecursive(FRONTEND_DIST);

	// Filter to only include production files (not dev artifacts)
	const prodFiles = files.filter(
		(f) =>
			f.endsWith(".html") ||
			f.endsWith(".js") ||
			f.endsWith(".css") ||
			f.endsWith(".svg") ||
			f.endsWith(".png") ||
			f.endsWith(".ico"),
	);

	if (prodFiles.length === 0) {
		console.error("No frontend files found. Run frontend build first.");
		process.exit(1);
	}

	// Generate the module
	let code = `/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by scripts/generate-embedded-assets.ts
 */

export interface EmbeddedAsset {
  content: string;
  mimeType: string;
  isBase64?: boolean;
}

export const frontendAssets: Record<string, EmbeddedAsset> = {
`;

	for (const file of prodFiles) {
		const filePath = join(FRONTEND_DIST, file);
		const ext = extname(file);
		const mimeType = getMimeType(file);

		// Read file content
		const isBinary = [".png", ".ico", ".woff", ".woff2"].includes(ext);

		// Normalize path separators for consistency (use forward slashes)
		const normalizedFile = file.replace(/\\/g, "/");

		if (isBinary) {
			const buffer = await readFile(filePath);
			const base64 = buffer.toString("base64");
			code += `  "${normalizedFile}": {
    content: "${base64}",
    mimeType: "${mimeType}",
    isBase64: true,
  },
`;
		} else {
			const content = await readFile(filePath, "utf-8");
			// Escape backticks and backslashes for template literal
			const escaped = content
				.replace(/\\/g, "\\\\")
				.replace(/`/g, "\\`")
				.replace(/\$\{/g, "\\${");
			code += `  "${normalizedFile}": {
    content: \`${escaped}\`,
    mimeType: "${mimeType}",
  },
`;
		}
	}

	code += `};

/**
 * Get the entry point HTML file
 */
export function getIndexHtml(): string {
  return frontendAssets["index.html"]?.content || "";
}

/**
 * Find the main App.js entry file (has hash in name)
 */
export function getAppJsPath(): string | undefined {
  return Object.keys(frontendAssets).find(
    (f) => f.startsWith("App.") && f.endsWith(".js") && !f.includes(".map")
  );
}
`;

	await writeFile(join(OUTPUT_DIR, "frontend-assets.ts"), code);
	console.log(`✓ Generated frontend-assets.ts with ${prodFiles.length} files`);
}

async function scanDirectoryFlat(dir: string): Promise<string[]> {
	try {
		const entries = await readdir(dir, { withFileTypes: true });
		const files: string[] = [];

		for (const entry of entries) {
			if (entry.isFile()) {
				files.push(entry.name);
			}
		}

		return files;
	} catch {
		return [];
	}
}

async function generatePromptsModule(): Promise<void> {
	const evaluatorFiles = await scanDirectoryFlat(PROMPTS_EVALUATORS);
	const sharedFiles = await scanDirectoryFlat(PROMPTS_SHARED);

	let code = `/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by scripts/generate-embedded-assets.ts
 */

export const evaluatorPrompts: Record<string, string> = {
`;

	for (const file of evaluatorFiles.filter((f) => f.endsWith(".md"))) {
		const filePath = join(PROMPTS_EVALUATORS, file);
		const content = await readFile(filePath, "utf-8");
		const escaped = content
			.replace(/\\/g, "\\\\")
			.replace(/`/g, "\\`")
			.replace(/\$\{/g, "\\${");
		const id = file.replace(".md", "");
		code += `  "${id}": \`${escaped}\`,
`;
	}

	code += `};

export const sharedPrompts: Record<string, string> = {
`;

	for (const file of sharedFiles.filter((f) => f.endsWith(".md"))) {
		const filePath = join(PROMPTS_SHARED, file);
		const content = await readFile(filePath, "utf-8");
		const escaped = content
			.replace(/\\/g, "\\\\")
			.replace(/`/g, "\\`")
			.replace(/\$\{/g, "\\${");
		const id = file.replace(".md", "");
		code += `  "${id}": \`${escaped}\`,
`;
	}

	code += `};

/**
 * Get evaluator prompt by ID
 */
export function getEvaluatorPrompt(id: string): string | undefined {
  return evaluatorPrompts[id];
}

/**
 * Get shared prompt by ID
 */
export function getSharedPrompt(id: string): string | undefined {
  return sharedPrompts[id];
}

/**
 * Get all evaluator IDs
 */
export function getEvaluatorIds(): string[] {
  return Object.keys(evaluatorPrompts);
}
`;

	await writeFile(join(OUTPUT_DIR, "prompts-assets.ts"), code);
	console.log(
		`✓ Generated prompts-assets.ts with ${evaluatorFiles.length} evaluators and ${sharedFiles.length} shared prompts`,
	);
}

async function main() {
	console.log("Generating embedded assets...\n");

	// Ensure output directory exists
	await mkdir(OUTPUT_DIR, { recursive: true });

	await generateFrontendModule();
	await generatePromptsModule();

	console.log("\n✓ All embedded assets generated successfully");
}

main().catch(console.error);
